### PR TITLE
🔧 Fixing Deprecation Warning 

### PR DESCRIPTION
**Pull request by C3n7ral051nt4g3ncy**
Regarding Issue #25 

This warning is raised when you try to get the event loop before running it.

I was getting also this Error:
```
/Users/xxxxxxx/mailcat/mailcat.py:1818: DeprecationWarning: There is no current event loop
  jobs = asyncio.gather(*[print_results(checker, target, req_session_fun, args.verbose) for checker in checkers])
```
**The fix works and I have tested it multiple times**.

### CODE REVIEW

**Comment by soxoj** [comment]
I see that you defined the new function in a top-level context, and then you are checking again if it's the call of the main. Suggest making all the new lines in the second nesting level, and just main without `if __name__=='main'` context

**Comment by C3n7ral051nt4g3ncy** [comment]
@soxoj I have taken off `Tutby`

**Comment by C3n7ral051nt4g3ncy** [comment]
@soxoj Please check script.
Now everything is working, no more errors anywhere.

Screen Shot 2023-04-25 at 23 54 48

**Comment by C3n7ral051nt4g3ncy** [comment]
@soxoj Please check the script. It seems everything is working nicely now.

**Comment by soxoj** [comment]
Checked, all good, thanks!

**Pull request merged**
